// Generated by CoffeeScript 1.6.2
(function() {
  var CANVAS_HEIGHT, CANVAS_WIDTH, MAX_RECURSION_DEPTH, minimumDotsDistance, pt1, pt2, pt3, pt4, t;

  CANVAS_WIDTH = CANVAS_HEIGHT = 1024;

  MAX_RECURSION_DEPTH = 300;

  pt1 = {
    x: 0 * CANVAS_WIDTH,
    y: 0.5 * CANVAS_HEIGHT
  };

  pt2 = {
    x: 1 * CANVAS_WIDTH,
    y: 0.5 * CANVAS_HEIGHT
  };

  pt3 = {
    x: 0.75 * CANVAS_WIDTH,
    y: 0.0 * CANVAS_HEIGHT
  };

  pt4 = {
    x: 0.4 * CANVAS_WIDTH,
    y: 0.5 * CANVAS_HEIGHT
  };

  t = 0.5;

  minimumDotsDistance = Math.pow(1 / 2, MAX_RECURSION_DEPTH);

  window.onload = function() {
    var context, drawCubicBezier, drawQuadraticBezier, pt;

    context = document.getElementById("sheet").getContext("2d");
    context.fillStyle = "black";
    context.beginPath();
    pt = function(x, y) {
      return context.fillRect(x, y, 1, 1);
    };
    pt(pt1.x * CANVAS_WIDTH, pt1.y * CANVAS_HEIGHT);
    pt(pt2.x * CANVAS_WIDTH, pt2.y * CANVAS_HEIGHT);
    drawQuadraticBezier = function(pt1, pt2, pt3) {
      var cuttingPlace1, cuttingPlace2, distanceX, distanceY, localMinimumDotsDistance, pointToDraw;

      distanceX = Math.abs(pt1.x - pt2.x);
      distanceY = Math.abs(pt1.y - pt2.y);
      localMinimumDotsDistance = Math.max(1, minimumDotsDistance);
      if (distanceX < localMinimumDotsDistance && distanceY < localMinimumDotsDistance) {
        return;
      }
      cuttingPlace1 = {
        x: pt1.x + (pt2.x - pt1.x) * t,
        y: pt1.y + (pt2.y - pt1.y) * t
      };
      cuttingPlace2 = {
        x: pt2.x + (pt3.x - pt2.x) * t,
        y: pt2.y + (pt3.y - pt2.y) * t
      };
      pointToDraw = {
        x: cuttingPlace1.x + (cuttingPlace2.x - cuttingPlace1.x) * t,
        y: cuttingPlace1.y + (cuttingPlace2.y - cuttingPlace1.y) * t
      };
      pt(pointToDraw.x, pointToDraw.y);
      drawQuadraticBezier(pt1, cuttingPlace1, pointToDraw);
      return drawQuadraticBezier(pointToDraw, cuttingPlace2, pt3);
    };
    drawCubicBezier = function(pt1, pt2, pt3, pt4) {};
    return drawQuadraticBezier(pt1, pt3, pt2);
  };

}).call(this);
